name=("Faizan")
DOB=("9 oct 2002")
age=(22)
year=(2025)
college=("madhav institute of technology")
print("my name is :",name)
print("date of birth:",DOB ,",age :",age ,",graduation compliting year:", year)
print("my college name is:" , college)
 print(type(DOB))